amicably-until-the-end/ShortTutoring_API

package-lock.json, package.json, src/config.discord-webhook.ts, src/uploads/uploads.controller.ts
- Discord 웹훅 라이브러리 추가
- 이후 에러 모니터링 등에 활용할 예정
-
-
=> ➕ Add discord-webhook

src/config.swagger.ts, src/requests/requests.controller.ts, src/responses/responses.controller.ts, src/responses/responses.service.ts, src/uploads/uploads.controller.ts, src/users/dto/create-user.dto.ts, src/users/users.controller.ts
=> Documentation

src/responses/responses.controller.ts, src/responses/responses.service.ts
- GET/ response API
- 해당 요청의 선생님 목록 반환
-
-
=> ➕ Add GET response

src/requests/dto/create-request.dto.ts, src/requests/entities/request.interface.ts, src/requests/entities/request.schema.ts, src/requests/requests.controller.ts, src/requests/requests.module.ts, src/requests/requests.service.ts, src/responses/responses.module.ts, src/responses/responses.service.ts
```json
{
"teacher_ids": [
"70ec9456-1030-4774-b84e-a22731e15426"
],
"created_at": "2023-07-10T08:12:14.425Z",
"problem": {
"school_level": "HighSchool",
"difficulty": "Easy",
"description": "I am having trouble with this problem",
"school_subject": "Mathematics_1",
"image_url": "Decoded image url",
"school_chapter": "Chapter_1"
},
"student_id": "b5aa3070-fbed-40fa-9310-b077832bb55f",
"id": "483acf2b-fd07-4cb3-852b-8b55c1abf896"
}
```
```json
[
{
"created_at": "2023-07-10T08:11:37.577Z",
"role": "teacher",
"bio": "lets study!",
"id": "70ec9456-1030-4774-b84e-a22731e15426",
"name": "teashort",
"profileImageURL": ""
}
]
```
```json
[
{
"id": "483acf2b-fd07-4cb3-852b-8b55c1abf896",
"student": {
"created_at": "2023-07-10T08:11:24.403Z",
"role": "student",
"bio": "lets study!",
"id": …
```
=> Refactor request

src/request/entities/request.schema.ts, src/request/request.service.ts, src/response/dto/select-response.dto.ts, src/response/response.service.ts, src/simulation/simulation.controller.ts, src/simulation/simulation.service.ts
- Fix #21 
> `/response` API 예외처리 추가 
- `/response/create` API 예외처리 추가 
- `/response/select` API 예외처리 추가
- `/response` API 예외처리 추가
- Request Scheme에 누락되었던
- `selectedTeacherId` 추가
- Swagger HTTP Response 상황별 안내 개선 필요
- HTTP Response DTO 리팩터링 필요
=> 🔨 Response API exception

src/request/dto/create-request.dto.ts, src/request/dto/response-request.dto.ts, src/request/request.controller.ts, src/request/request.service.ts
* #24 
- /request/create 버그 픽스
- /request/create에서 studentId가 아닌 requestId를 받는 문제 해결
- /request/create 요청시 Problem 객체로 전달하는 것이 편할 지?
- 논의 후 결정
=> 🔨 Fix /request/create

src/request/dto/delete-request.dto.ts, src/request/request.controller.ts, src/request/request.service.ts, src/response/response.controller.ts, src/response/response.service.ts, src/simulation/simulation.controller.ts
* #26 
- /request API들 내부 학생 | 선생님 권한 구분
- /response API들 내부 학생 | 선생님 권한 구분
권한이 없는 사용자가 API 호출시 `403 Forbidden` 반환
- 인증 시급
=> ⭐ 권한 예외처리 추가

src/simulation/simulation.controller.ts, src/simulation/simulation.service.ts
* 튜터링 매칭 시뮬레이션 시나리오
- /response/select 학생의 선생님 선택
> 해당 과정 시뮬레이션
- 웹훅으로 Json 형식 공유
업슈
=> ⭐ 학생의 선생님 선택 시뮬레이션 + 웹훅

src/tutoring/tutoring.controller.ts, src/upload/upload.controller.ts
* 클라이언트 입장에서 불필요한 엔드포인트가 있음 (e.g. /upload, /tutoring/create)
* 클라이언트 입장에서 불필요한 엔드포인트 정리
- /upload 삭제
- /tutoring 삭제
없슈
=> [ST-350] 🔍 API 엔드포인트 정리

src/request/dto/response-request.dto.ts, src/request/entities/request.schema.ts, src/user/entities/user.entity.ts, src/user/entities/user.interface.ts, src/user/entities/user.schema.ts, src/user/user.controller.ts
* /request/list의 Response 예시와 실제가 다름
- User 객체의 created_at 속성명 수정
- Request 객체의 created_at 객체명 수정
- /request/list의 Response 형식 통일
업슈
=> [ST-359] 🔨 /request/list Response 예시 수정

src/simulation/simulation.service.ts
* 디버깅 작업시 튜터링 객체 관리
- /simulation/select 실행시 사용자 프로필 생성
- /simulation/getAll 반환 데이터에 Tutoring 객체 추가
- /simulation/removeAll 삭제 대상에 Tutoring 객체 추가
- 선택 시뮬레이션시 사용자 프로필 생성
- 관리자 도구 사용시 Tutoring 관리 추가
미해결 이슈, 발견한 이슈
=> [ST-364] ⭐️ 튜터링 목록 가져오기 및 초기화

src/agora/agora.module.ts, src/agora/agora.service.ts, src/response/response.module.ts, src/response/response.service.ts, src/simulation/simulation.module.ts, src/simulation/simulation.service.ts, src/tutoring/dto/create-tutoring.dto.ts, src/tutoring/entities/tutoring.interface.ts, src/tutoring/entities/tutoring.schema.ts, src/tutoring/tutoring.module.ts, src/tutoring/tutoring.service.ts, src/user/user.module.ts
[ST-373] 아고라 토큰 발급
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> [ST-373] response/check 하면 Agora Whiteboard token. 전달

src/app.module.ts, src/auth/auth.controller.ts, src/auth/auth.repository.ts, src/auth/auth.service.ts, src/auth/dto/get-accesstoken.dto.ts, src/auth/entities/auth.entity.ts, src/config.swagger.ts, src/offer/offer.controller.ts, src/question/question.controller.ts, src/user/user.controller.ts, src/user/user.service.ts
* 안드로이드 SDK 활용에 대응한 로그인 방식 수정
- 기존 authorization code 기반 로그인 방식 수정
- access token 기반으로 수정
- 엔드포인트 정리
- Cloud Front로 발급받은 URL로 수정
- 문서화 작업
=> [ST-440] 로그인 API (authorization code > access token)

src/app.module.ts, src/user/descriptions/user.operation.ts, src/user/dto/login-user.dto.ts, src/user/user.controller.ts, src/user/user.service.ts
* 로그인 API POST로 변경
- access token 앞 `Bearer` 추가
- 회원가입 API
- 로그인 API
- 로그인 POST 변경
- 로그인 DTO 생성
- 회원가입 및 로그인 버그
없슈
=> [ST-448] ⭐ 로그인 API 변경 (GET > POST)

src/app.module.ts, src/user/descriptions/user.operation.ts, src/user/descriptions/user.response.ts, src/user/dto/create-user.dto.ts, src/user/user.controller.ts, src/user/user.repository.ts, src/user/user.service.ts
* 회원가입 분기
- /user/signup/student
- /user/signup/teacher
- 회원가입시 학생, 선생님 각각 입력받는 정보가 달라 엔드포인트 분기
- 없슈
=> ⭐ 회원가입시 학생|선생님 분기

src/auth/auth.controller.ts, src/auth/auth.repository.ts, src/auth/auth.service.ts, src/offer/offer.controller.ts, src/offer/offer.repository.ts, src/offer/offer.service.ts, src/question/entities/question.interface.ts, src/question/entities/question.schema.ts, src/question/question.controller.ts, src/question/question.repository.ts, src/question/question.service.ts, src/user/user.service.ts
fix #41 
- UserKey 관련 리팩터링
- 버그 픽스
- UserKey 관련 리팩터링
- 회원가입 관련 버그 픽스
- 없을슈도?
=> [ST-478] 🔨 회원가입 버그 픽스

src/chatting/chatting.controller.ts, src/chatting/chatting.module.ts, src/chatting/chatting.repository.ts, src/chatting/chatting.service.ts, src/chatting/description/chatting.operation.ts, src/chatting/description/chatting.query.ts, src/chatting/description/chatting.response.ts, src/chatting/dto/create-chatting.dto.ts, src/chatting/entities/chatting.interface.ts, src/chatting/entities/chatting.schema.ts, src/question/entities/question.interface.ts, src/question/entities/question.schema.ts, src/question/question.repository.ts, src/user/entities/user.interface.ts, src/user/entities/user.schema.ts, src/user/user.repository.ts
ST-573
채팅 목록 가져오기 API를 작성했습니다. 
업데이트 내역 작성
/src/chatting 
채팅 스키마 재정의 
/scr/question
question schema 
1. isSelect 항목 추가 : true이면 지정질문, false이면 일반 질문
2. participantingChattingRooms: Chatting Item의 아이디 리스트로 수정 
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> [ST-573] 채팅 목록 불러오기 API

src/chatting/chatting.service.ts, src/offer/dto/accept-offer.dto.ts, src/offer/offer.controller.ts, src/offer/offer.repository.ts, src/offer/offer.service.ts
[일반 질문에서 학생이 선생님 선택할 때 시간 확정하는 것으로 API 변경]
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=>  [ST-625] Feat/normal question

package-lock.json, package.json, src/config.firebase.ts, src/main.ts, src/redis/redis.module.ts, src/redis/redis.repository.ts, src/socket/socket.gateway.ts, src/user/dto/setFCMToken-user.dto.ts, src/user/user.controller.ts, src/user/user.service.ts
FCM 푸시 메시지 백엔드 구현
- FCM 푸시 기능 구현
- 레디스 자료구조 변경
```json
"example-userA-id": {
"socketId": "example-socketA-id",
"fcmToken": "example-fcm-tokenA"
},
"example-userB-id": {
"socketId": "example-socketB-id",
"fcmToken": "example-fcm-tokenB"
}
...
```
=> [ST-648] FCM 푸시 메시지

src/user/entities/user.interface.ts, src/user/entities/user.schema.ts, src/user/user.controller.ts, src/user/user.repository.ts, src/user/user.service.ts
프로필 내 잔여 코인 정보 제공
코인 수령 API
위와 동
=> [ST-663] 코인 관련 엔티티 정의 및 API 엔드포인트 추가

src/offer/offer.service.ts, src/question/question.service.ts, src/socket/socket.gateway.ts, src/socket/socket.module.ts, src/socket/socket.repository.ts, src/tutoring/tutoring.service.ts, src/user/dto/create-user.dto.ts, src/user/entities/user.interface.ts, src/user/user.repository.ts, src/user/user.service.ts
공통 -> profile img 추가
선생님 -> 학년, 단과대 삭제
User 엔티티 내려줄 때 followersCnt 내려 주는 걸 followers(student id list)로 바꾸기
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> [ST-641] Feat/signup user profile img

src/tutoring/tutoring.repository.ts, src/user/descriptions/user.response.ts, src/user/entities/user.entities.ts, src/user/user.controller.ts, src/user/user.module.ts, src/user/user.service.ts
user/following, user/followers 수정
Reponse format 변경, 선생님의 경우 누적 과외 수 같이 전달.
Tutoring repository 가 필요함에 따라서 service단에서 데이터 가공.
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> [ST-671] user/following, user/followers 수정

src/tutoring/tutoring.service.ts
수업 시작하면 학생한테 메시지 보내주기
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> [ST-687] 수업 시작하면 학생한테 메시지 보내주기

src/question/descriptions/question.query.ts, src/question/question.repository.ts, src/question/question.service.ts, src/tutoring/tutoring.service.ts, src/user/user.repository.ts
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> [ST-672] Feat/purchase coin

src/user/descriptions/user.response.ts, src/user/entities/user.entities.ts, src/user/user.service.ts
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> Fix/online 선생님 response 속성 추가

src/agora/agora.service.ts, src/tutoring/tutoring.service.ts
make rtc toke without proper uid
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> fix error - make rtc toke without proper uid

src/tutoring/tutoring.service.ts
* Feature # (issue)   
선생님이 이미 시작한 수업에 다시 들어가는 경우에 메시지 보내지 않음
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> fix/ start again

src/question/question.service.ts
fix/ 지정 질문 올리면 만들어진 채팅 아이디 알려줌
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> fix/ 지정 질문 올리면 만들어진 채팅 아이디 알려줌

src/user/user.repository.ts
* 무료 코인 지급 주기 변경
24시간 기준 > 자정 기준
=> [ST-748] 무료 코인 지급 주기 변경

src/user/user.controller.ts
=> [ST-778] /user/tutoring/list 수정

src/agora/agora.module.ts, src/agora/agora.service.ts, src/tutoring/entities/tutoring.interface.ts, src/tutoring/entities/tutoring.schema.ts, src/tutoring/tutoring.controller.ts, src/tutoring/tutoring.repository.ts, src/tutoring/tutoring.service.ts, src/upload/upload.repository.ts, src/user/descriptions/user.response.ts, src/user/entities/user.entities.ts, src/user/user.controller.ts, src/user/user.service.ts
* feat/ base work for recording
* feat/ base work for recording
* feat/ start record and finish record tutoring
* 🔨 /user/tutoring/list 수정
* 🔨 /user/tutoring/list 수정
* feat/ start record and finish record tutoring
* Update tutoring.repository.ts
---------
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> Feat/과외 녹화 추가 (#96)

src/response.ts, src/tutoring/tutoring.service.ts
response fail errorcode 추가
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> feat/add errorCode 

package.json
prod 서버 --watch 옵션 없어서 배포시 귀찮음
(git pull하고 npm 죽이고 다시 켜야됨 ㄹㅇ)
=> 🔨 prod 명령어 --watch 옵션 추가

src/tutoring/tutoring.service.ts
classroom info 오류 픽스
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> fix/ append omitted "await"

src/config.redis.ts, src/redis/redis.repository.ts, src/socket/socket.gateway.ts
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> setting redis for dev

src/tutoring/tutoring.service.ts
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> question status finished 추가

src/chatting/chatting.repository.ts, src/question/descriptions/question.query.ts, src/question/question.controller.ts, src/question/question.service.ts
/question/list/my 학생과 선생님 모두 조회 가능
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> feat/ edit api - /question/list/my 학생과 선생님 모두 조회 가능

src/response.ts
errorCode가 data 안으로 들어가는 이슈 해결
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> errorCode가 data 안으로 들어가는 이슈 해결

src/question/question.service.ts
업데이트 내역 작성
해결한 문제 등 이슈
미해결 이슈, 발견한 이슈
=> question/list/my 가 선생님이 선택되지 않은 일반 질문을 안 불러오는 것 수정

src/offer/offer.service.ts, src/tutoring/tutoring.service.ts
업데이트 내역 작성
해결한 문제 등 이슈
일반 질문 이미 예약 되어 있는 문제를 또 예약 하는 경우 수정
미해결 이슈, 발견한 이슈
=> hotfix/일반 질문 이미 예약 되어 있는 문제를 또 예약 하는 경우 수정

src/auth/auth.service.ts, src/chatting/chatting.service.ts, src/config.discord-webhook.ts, src/event/event.service.ts, src/offer/offer.service.ts, src/question/question.service.ts, src/socket/socket.gateway.ts, src/socket/socket.repository.ts, src/tutoring/tutoring.service.ts, src/upload/upload.repository.ts, src/user/user.repository.ts, src/user/user.service.ts
디스코드 웹훅 추가
디버깅 메시지 수정
각 인스턴스 `.env` 파일들 좀 건드렸는데..
아무 일도 없었으면 좋겠다
편한 디버깅 가능
없슈
아직까지는...
=> [ST-827] 디버깅 웹훅 추가 및 수정
